### ISSUE TITLE
[Feature]: Add jest and write tests for scripts/extractSlideData.js

### ISSUE THREAD

**Issue by AhsanAyaz** [AhsanAyaz/slides#14] opened 2023-10-27 14:36 UTC
Right now, we don't have any tests in the repository. And we have the `scripts/extractSlideData.js` file which can have unit tests. The task is to write these unit tests.

**Comment by Rachit1313** [comment] 2023-10-27 17:40
I would like to work on this

**Comment by anttijankeri** [comment] 2023-10-27 20:05
Please assign the task to me.

**Comment by Rachit1313** [comment] 2023-10-27 20:11
Hey @anttijankeri , Sorry but I already started working on this part and created the test functions for extractTitle. Is it possible for you work on some other issue?

**Comment by Rachit1313** [comment] 2023-10-28 12:05
Hi @AhsanAyaz , Could you please review and let me know if any changes are required?

**Comment by AhsanAyaz** [comment] 2023-10-29 21:56
@Rachit1313 I've merged your PR but even though we use jest, the `test` command doesn't include jest. It still runs `gulp test` behind the scenes. But also has an issue with the tests in windows:
![image](https://github.com/AhsanAyaz/slides/assets/9844254/7e697f9c-1079-4a43-becb-9957d32d01d4)

**Comment by AhsanAyaz** [comment] 2023-10-29 21:56
@anttijankeri  maybe you can have a look?

**Comment by Rachit1313** [comment] 2023-10-29 21:59
> @Rachit1313 I've merged your PR but even though we use jest, the `test` command doesn't include jest. It still runs `gulp test` behind the scenes. But also has an issue with the tests in windows:
> 
> ![image](https://github.com/AhsanAyaz/slides/assets/9844254/7e697f9c-1079-4a43-becb-9957d32d01d4)
> 
> 

As I can confirm in the screenshot provided, The difference here is that the function returned the path with // i.e windows formatting for a path whereas I created the functions in a macOS.
This can be fixed by adding another statement of checking equal to mac version or windows output.

@anttijankeri hope this helps!
Let me know if you want me to make the changes.

**Comment by Rachit1313** [comment] 2023-10-29 22:00
> @Rachit1313 I've merged your PR but even though we use jest, the `test` command doesn't include jest. It still runs `gulp test` behind the scenes. But also has an issue with the tests in windows:
> 
> ![image](https://github.com/AhsanAyaz/slides/assets/9844254/7e697f9c-1079-4a43-becb-9957d32d01d4)
> 
> 

For the gulp test.
That's because test script was already setup for gulp in the package.json. I wasn't sure if you wanted me to update it or not.

Let me know if you want me to change that.

**Comment by anttijankeri** [comment] 2023-10-30 10:33
Ive fixed the problems from earlier. The windows thing may or may not work, cant test it atm.

**Closed as completed** 2023-10-30 14:11 UTC
Labels: hacktoberfest
